## Chrome — the one autoload for furniture that must be true on EVERY screen,
## not just the ones a scene file happens to carry it on.
##
## TODAY THAT MEANS ONE THING: the negative brand mark, upper-left, on every
## screen (owner, playtest StartPageSept7). Placement was previously an open
## question -- docs/DECISIONS.md item 17 records "negative mark upper-left on
## desktop/TV" as the SPECIFIED-but-undecided option; this request decides it.
##
## WHY AN AUTOLOAD AND NOT A NODE IN EACH .tscn. The same argument Style.gd
## already makes for the theme: `change_scene_to_file()` throws away and
## rebuilds the ENTIRE current-scene tree, so anything living inside one of
## the nine scene files would need to be added nine separate times and would
## need adding again for the tenth screen this project ever grows. An autoload
## sits outside that tree; add its CanvasLayer straight onto the SceneTree's
## own root Window in _ready() and it survives every scene swap for free,
## already-drawn, before the tenth screen is even a file.
##
## CONTRAST IS MEASURED AND MARGINAL, NOT SOLVED. scripts/check_brand_contrast.py
## found 53% of the negative mark's ink at or below 2.5:1 against CYM's slate
## ground (docs/DECISIONS.md item 17, Session 33). That is a property of the
## artwork, not of this wiring -- fixing it means re-pitching fill values on
## the source SVG, a decision for whoever owns the mark, not a default this
## file should invent. Flagged here so the next reader does not have to
## re-derive it from a screenshot.

extends Node

## Generated by scripts/build_brand.py from brand/NEWnegative_CYM.svg --
## DO NOT EDIT BY HAND. Re-run that script if the source mark changes;
## scripts/build_brand.py --check fails loudly if this has drifted from it.
const LOGO_PATH: String = "res://assets/brand/negative_mark.svg"

## The mark's native aspect (viewBox 223x374, roughly 0.6:1 wide:height).
## Capped by HEIGHT rather than width: a corner mark that's this tall and
## narrow reads as a vertical strip if capped by width instead, and a fixed
## height keeps it visually level with the title bar text beside it on
## screens that have one (CaseDisplay, MysteryTitleLabel).
const LOGO_HEIGHT: float = 48.0
const MARGIN: float = Palette.SPACE_BASE


func _ready() -> void:
	if not ResourceLoader.exists(LOGO_PATH):
		push_warning("Chrome: %s is missing -- run: python3 scripts/build_brand.py" % LOGO_PATH)
		return
	var texture: Texture2D = load(LOGO_PATH) as Texture2D
	if texture == null:
		return

	var layer := CanvasLayer.new()
	# Above ordinary screen content, below anything a future modal/dialog
	# layer might need -- there is only one layer today, so this is headroom,
	# not a real ordering claim yet.
	layer.layer = 10

	var rect := TextureRect.new()
	rect.texture = texture
	rect.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT
	var aspect: float = texture.get_width() / float(texture.get_height())
	rect.custom_minimum_size = Vector2(LOGO_HEIGHT * aspect, LOGO_HEIGHT)
	rect.size = rect.custom_minimum_size
	rect.position = Vector2(MARGIN, MARGIN)
	# Decorative chrome, not a control -- a click must reach whatever is
	# underneath it (a screen's own back/menu button, if one is ever placed
	# near the corner) rather than being swallowed here.
	rect.mouse_filter = Control.MOUSE_FILTER_IGNORE

	layer.add_child(rect)
	get_tree().root.add_child(layer)
